# https://protonvpn.com/support/official-linux-vpn-debian/
# wget https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.8_all.deb
# "Please don’t try  to check the GPG signature of this release package (dpkg-sig –verify). Our internal release process is split into several parts; the release package is signed with a GPG key, and the repo is signed with another GPG key. So the keys don’t match."
# echo "0b14e71586b22e498eb20926c48c7b434b751149b1f2af9902ef1cfe6b03e180 protonvpn-stable-release_1.0.8_all.deb" | sha256sum --check -
# sudo dpkg -i ./protonvpn-stable-release_1.0.8_all.deb && sudo apt update
#
# https://protonvpn.com/support/linux-cli
# sudo apt install proton-vpn-cli

# TODO
# * Specify the package version statically in code.
# * Have a notification mechanism about a more recent version being available.
#   * The notification should abort the Ansible run to draw attention.
#   * It needs to be possible to configure the notification tasks to be skipped
#     by changing a single line.

- name: Announce to be not yet implemented
  debug:
    msg: proton-vpn-cli install not yet implemented

# grep '^Filename:.*protonvpn-stable-release.*\.deb$' ~/Downloads/Packages
# - name: Download 
#   ansible.builtin.get_url:
#     url: https://repo.protonvpn.com/debian/dists/stable/main/binary-all/Packages
#     dest: # /tmp/fleet-management/provision
#     mode:
#     # url: http://example.com/path/file.conf
#     # dest: /etc/foo.conf
#     # mode: '0440'

# {{ deb_protonvpn_meta_install }} # protonvpn-stable-release_1.0.8_all.deb

# TODO test
#
# Test idea:
# 1. Store public IP address
# 2. Read credentials from password manager
# 3. Login
# 4. Connect
# 5. Verify that current public IP address is not the stored IP address
# 6. Disconnect
#
# https://linuxconfig.org/how-to-use-curl-to-get-public-ip-address
# https://github.com/rdegges/ipify-api
# https://www.ipify.org/
